#!/usr/bin/env bash 

set -e  
#making sure we can properly use sudo
echo "updating...."
sudo nixos-rebuild switch --flake .#temporaryOS  --show-trace --print-build-logs --verbose

if [ "$?" -ne 0 ]
  then echo "exiting because of error during update"

  exit
fi
  

echo "commiting everything to git"
git add . 
gen=$(nixos-rebuild list-generations | grep True|head -c 5 )
git commit -m "$gen"
echo "done, gen $gen has been succsessfully commited"
exit
