#!/bin/bash
while true; do
  
  (WALLPAPER=$(ls -1 /etc/nixos/wallpaper | sort -R | head -n 1) 
  hyprctl hyprpaper preload /etc/nixos/wallpaper/$WALLPAPER  
  hyprctl hyprpaper wallpaper ,/etc/nixos/wallpaper/$WALLPAPER)
  sleep 300
done

